# Generated by Django 5.1.1 on 2025-01-14 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_creted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
